### ISSUE TITLE
[PF1] BAB and CMB are mislabeled in the HUD

### ISSUE THREAD

**Issue by mkahvi** [Drental/fvtt-tokenactionhud#315]
Missing localize, or missing language keys.

![Screenshot 2022-10-23 023908](https://user-images.githubusercontent.com/8120158/197366298-b07caef4-2fd6-4058-801e-02c3423457cf.png)

```yaml
TAH: 3.0.12
PF1: 0.82.2
Foundry: 10.288
```
