### ISSUE TITLE
[PF1] Custom unparented skills use invalid skill ID

### ISSUE THREAD

**Issue by mkahvi** [Drental/fvtt-tokenactionhud#334]
For example, if I create skill `piloting`, it appears as using ID `undefined.subSkills.piloting` in TAHUD, which obviously breaks rolling the skill that should be simply `piloting`.

Subskills work fine, this is not about them.

```yaml
TAHUD: 3.0.15
PF1: 0.82.2
Foundry: 10.290
```

Simple repro:
- Hit add skill at bottom of skills tab, create new skill
- Attempt to roll it via TAHUD.
